# -*- coding: utf-8 -*-
"""
Author: Simon Kaemmer

This script takes a file generated by .\accesschk64.exe -uwds Users c:\* > 'C:\...\output.txt'
and prints where executable files are located (.exe, .dll, .bat, .msi).

"""

import os, locale

r = open("executables.txt", "w")


def find_executable(path):
    for file in os.listdir(path):
        if file.endswith(".exe") or file.endswith(".bat") or file.endswith(".dll") or file.endswith(".msi"):
            print(os.path.join(path, file))
            r.write(os.path.join(path, file) + "\n")

f = open("ausgabe.txt", "r", encoding=locale.getdefaultlocale()[1])
for i in range(7):
    next(f)

p = open("pausgabe.txt", "w+")
for line in f:
    path = line[7:].replace("\n", "").replace(chr(0), "").replace("\\", "/")
    if(path != "\"\""):
        p.write(path + "\n")

p.close()
f.close()

p = open("pausgabe.txt", "r")


for line in p:
    if len(line) > 1:
        find_executable(line.replace("\n", ""))

p.close()
r.close()


    
